 Traceback (most recent call last):
  File "/Users/lindsayyoung/.virtualenvs/newfec/bin/rdbms-subsetter", line 9, in <module>
    load_entry_point('rdbms-subsetter==0.2.5', 'console_scripts', 'rdbms-subsetter')()
  File "/Users/lindsayyoung/.virtualenvs/newfec/lib/python3.4/site-packages/subsetter.py", line 533, in generate
    source.create_subset_in(target)
  File "/Users/lindsayyoung/.virtualenvs/newfec/lib/python3.4/site-packages/subsetter.py", line 425, in create_subset_in
    prioritized=prioritized)
  File "/Users/lindsayyoung/.virtualenvs/newfec/lib/python3.4/site-packages/subsetter.py", line 297, in create_row_in
    row_exists = pks in target.pending or pks in target.done
TypeError: unhashable type: 'list' 
